### ISSUE TITLE
libnfporb is GPLv3 and can't be used in an MIT licensed project

### ISSUE THREAD

**Issue by kallaballa** [zjl9959/ClothCutting#8]
Hi! I am the original author of libnfporb which is licensed GPLv3. You are using it in your project which you licensed MIT - that contradicts the license of libnfporb. How would you like to resolve this issue?

**Comment by zjl9959** [comment]
Hi, thanks for reminder, I have changed my license into GPLv3.

**Comment by kallaballa** [comment]
That is so awesome. Thanks!
